name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'

jobs:
  Deploy-Resources:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: DeployBicepFile
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
          resourceGroupName: ${{ vars.RG_NAME }}
          template: ./InfrastructureAsCode/main.bicep
          parameters: environment=${{ github.event.inputs.environment }}
        
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.DeployBicepFile.outputs.application_name }}
          slot-name: 'production' # optional
          # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.ACR_LOGIN_SERVER }}/wth/dotnetcoreapp:12'