name: Deploy

on:
    workflow_dispatch:

jobs:
    Deploy-Resources:
        runs-on: ubuntu-latest

        steps:
            - name: Set up Azure CLI
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy Azure Resource Manager
              uses: azure/CLI@v1
              with:
                azcliversion: 2.28.0
                inlineScript: |
                  ls
                  az deployment sub create --location uksouth --template-file /wth-team17/InfrastructureAsCode/main.bicep

