name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
          - name: Set up Azure CLI
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
